f = open("big.txt", "r")
fpos = f.tell()
print("Doc toi vi tri: ", fpos)
line = f.readline()
print(line, end = '')
fpos = f.tell()
print("Doc toi vi tri: ", fpos)
line = f.readline()
print(line, end = '')
fpos = f.tell()
print("Doc toi vi tri: ", fpos)
