row_1 = '+ {:-<6} + {:-^15} + {:->10} +' .format('', '', '')
row_2 = '| {:<6} | {:^15} | {:>10} |' .format('ID', 'Name', 'Address')
row_3 = '| {:<6} | {:^15} | {:>10} |' .format('K502', 'Ozawa', 'Japan')
row_4 = '| {:<6} | {:^15} | {:>10} |' .format('BJ69', 'Yui Hatano', 'Japan')
row_5 = '+ {:-<6} + {:-^15} + {:->10} +' .format('', '', '')
print(row_1)
print(row_2)
print(row_3)
print(row_4)
print(row_5)	